"""Add reference_id to message

Revision ID: 7aae9a20b651
Revises: fa4a7b856dca
Create Date: 2026-07-15 17:37:10.205620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aae9a20b651'
down_revision = 'fa4a7b856dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_message_reference_id'), ['reference_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_reference_id'))
        batch_op.drop_column('reference_id')

    # ### end Alembic commands ###
