"""Add amount column to message

Revision ID: e804b71a11e5
Revises: 7aae9a20b651
Create Date: 2026-07-15 18:42:38.760556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e804b71a11e5'
down_revision = '7aae9a20b651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.create_index(batch_op.f('ix_message_amount'), ['amount'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_amount'))
        batch_op.drop_column('amount')

    # ### end Alembic commands ###
