"""initial schema

Revision ID: fa4a7b856dca
Revises: 
Create Date: 2026-07-14 12:47:59.809563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa4a7b856dca'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_admin_user_username'), ['username'], unique=True)

    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('actor_type', sa.String(length=20), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('actor_label', sa.String(length=120), nullable=True),
    sa.Column('target_type', sa.String(length=40), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor_created', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_audit_event_created', ['event_type', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_log_event_type'), ['event_type'], unique=False)

    op.create_table('end_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_admin_id'], ['admin_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_end_user_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_end_user_status'), ['status'], unique=False)

    op.create_table('device',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('device_name', sa.String(length=120), nullable=True),
    sa.Column('manufacturer', sa.String(length=80), nullable=True),
    sa.Column('model', sa.String(length=80), nullable=True),
    sa.Column('android_version', sa.String(length=20), nullable=True),
    sa.Column('app_version_name', sa.String(length=20), nullable=True),
    sa.Column('app_version_code', sa.Integer(), nullable=True),
    sa.Column('api_token_hash', sa.String(length=128), nullable=False),
    sa.Column('token_created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('token_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('registered_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=False),
    sa.Column('end_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['end_user_id'], ['end_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_api_token_hash'), ['api_token_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_end_user_id'), ['end_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_is_online'), ['is_online'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_last_seen_at'), ['last_seen_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_registered_at'), ['registered_at'], unique=False)

    op.create_table('message',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.String(length=36), nullable=False),
    sa.Column('end_user_id', sa.Integer(), nullable=True),
    sa.Column('sender_raw', sa.String(length=32), nullable=False),
    sa.Column('sender_matched', sa.String(length=32), nullable=False),
    sa.Column('message_body', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=10), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('client_message_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['end_user_id'], ['end_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'client_message_id', name='uq_message_device_client_id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_category'), ['category'], unique=False)
        batch_op.create_index('ix_message_category_received', ['category', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_message_device_received', ['device_id', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_end_user_id'), ['end_user_id'], unique=False)
        batch_op.create_index('ix_message_enduser_received', ['end_user_id', 'received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_received_at'), ['received_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_uploaded_at'), ['uploaded_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_message_received_at'))
        batch_op.drop_index('ix_message_enduser_received')
        batch_op.drop_index(batch_op.f('ix_message_end_user_id'))
        batch_op.drop_index('ix_message_device_received')
        batch_op.drop_index(batch_op.f('ix_message_device_id'))
        batch_op.drop_index('ix_message_category_received')
        batch_op.drop_index(batch_op.f('ix_message_category'))

    op.drop_table('message')
    with op.batch_alter_table('device', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_registered_at'))
        batch_op.drop_index(batch_op.f('ix_device_last_seen_at'))
        batch_op.drop_index(batch_op.f('ix_device_is_online'))
        batch_op.drop_index(batch_op.f('ix_device_end_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_api_token_hash'))

    op.drop_table('device')
    with op.batch_alter_table('end_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_end_user_status'))
        batch_op.drop_index(batch_op.f('ix_end_user_created_at'))

    op.drop_table('end_user')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))
        batch_op.drop_index('ix_audit_event_created')
        batch_op.drop_index('ix_audit_actor_created')

    op.drop_table('audit_log')
    with op.batch_alter_table('admin_user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_user_username'))
        batch_op.drop_index(batch_op.f('ix_admin_user_email'))

    op.drop_table('admin_user')
    # ### end Alembic commands ###
